#!/bin/bash

#this is for sundanceVR job, ripping the SAR and DAR out of the metadata

infile=$1

oufile=$2

ffmpeg=/software/ffmpeg/2.8.3/linux.centos6.x86_64/bin/ffmpeg

if [ "$#" -ne 2 ]; then
    echo -e "\nRequires an input and output file!\n Ex: aspect_fix inputfile.mov outputfile.mov\n"
    exit
fi

if [ ! -e $1 ]; then
    echo -e "\nInput file $1 does not exist.. are you in the right directory?\n"
    exit
fi



#this is the command
$ffmpeg -i $1 -c:a copy -c:v copy -aspect 1:1 $2
