#!/bin/bash

# Use flock to stay within licensing agreements for photoscan-pro
# Makes lockfile over NFS, should release upon exit, or if caught by trap in _prepare_locking()
# bryce-e@.com | 2015-08-26
# Template of this taken from: 
## Copyright (C) 2009  Przemyslaw Pawelczyk <przemoc@gmail.com>
## License: GNU General Public License v2, v3

### HEADER ###

PSPRO="/software/engineering/photoscan/1.1.6/photoscan-pro/photoscan.sh"
LOCKFILE="/software/engineering/tools/locks/`basename $0`"
LOCKFD=99
LICENSE="/etc/xdg/Agisoft/PhotoScan Pro.conf"

# PRIVATE
_lock()             { flock -$1 $LOCKFD; }
_no_more_locking()  { _lock u; _lock xn && rm -f $LOCKFILE; }
_prepare_locking()  { eval "exec $LOCKFD>\"$LOCKFILE\""; trap _no_more_locking EXIT; }

# ON START
[ -e "$LICENSE" ] || { echo "No license file"; exit 1; }
_prepare_locking

# PUBLIC
exlock_now()        { _lock xn; }  # obtain an exclusive lock immediately or fail
exlock()            { _lock x; }   # obtain an exclusive lock
shlock()            { _lock s; }   # obtain a shared lock
unlock()            { _lock u; }   # drop a lock

### BEGIN SCRIPT ###

exlock_now || { echo "$(stat -c '%U' $LOCKFILE) is already using photscan pro (lockfile owner), there is 1 license for this software "; exit 1; } 
$PSPRO

